# frozen_string_literal: true

source "https://rubygems.org"

ruby RUBY_VERSION

gemspec

RECAPTCHA_DECIDIM_VERSION = { git: "https://github.com/CodiTramuntana/decidim", branch: "release/0.29-stable" }.freeze

gem "decidim", RECAPTCHA_DECIDIM_VERSION

gem "recaptcha"

group :development, :test do
  gem "bootsnap", require: true
  gem "byebug", platform: :mri
  gem "faker"
  gem "listen"
end
