version: '2'
services:
  app:
    build:
      context: .
      args:
        rails_env: development
    volumes:
      - .:/code
    environment:
      - DB_HOST=pg
      - DB_USERNAME=postgres
    ports:
      - 3000:3000
    links:
      - pg
      - redis
    command: sh entrypoint.sh
  pg:
    image: postgres
    volumes:
      - pg-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
  redis:
    image: redis
    volumes:
      - redis-data:/data
volumes:
  pg-data:
  redis-data:
