# frozen_string_literal: true

source "https://rubygems.org"

ruby RUBY_VERSION

PROCESS_EXTENDED_DECIDIM_VER = { git: "https://github.com/CodiTramuntana/decidim", branch: "release/0.24-stable" }.freeze

gem "decidim", PROCESS_EXTENDED_DECIDIM_VER
gem "decidim-process-extended", path: "."
gem "decidim-type", path: "../decidim-type"

gem "bootsnap", "~> 1.4"
gem "puma", ">= 4.3"
gem "uglifier", "~> 4.1"

group :development, :test do
  gem "byebug", "~> 11.0", platform: :mri

  gem "decidim-dev", PROCESS_EXTENDED_DECIDIM_VER
end

group :development do
  gem "faker", "< 3"
  gem "letter_opener_web", "~> 1.3"
  gem "listen", "~> 3.1"
  gem "spring", "~> 2.0"
  gem "spring-watcher-listen", "~> 2.0"
  gem "web-console", "~> 3.5"
end
