# frozen_string_literal: true

begin
  require "bundler/setup"
rescue LoadError
  puts "You must `gem install bundler` and `bundle install` to run rake tasks"
end

require "rdoc/task"

RDoc::Task.new(:rdoc) do |rdoc|
  rdoc.rdoc_dir = "rdoc"
  rdoc.title = "Decidim::Process::Extended"
  rdoc.options << "--line-numbers"
  rdoc.rdoc_files.include("README.md")
  rdoc.rdoc_files.include("lib/**/*.rb")
end

require "decidim/dev/common_rake"

desc "Generates a dummy app for testing"
task test_app: "decidim:generate_external_test_app" do
  app_yml = File.join("spec", "decidim_dummy_app", "config", "application.yml")
  FileUtils.mkdir_p(File.dirname(app_yml))
  FileUtils.touch(app_yml)
end

desc "Generates a development app."
task development_app: "decidim:generate_external_development_app"
