# frozen_string_literal: true

source "https://rubygems.org"

ruby RUBY_VERSION

TOP_COMMENTS_DECIDIM_VERSION = { git: "https://github.com/CodiTramuntana/decidim", branch: "release/0.29-stable" }.freeze

gem "decidim", TOP_COMMENTS_DECIDIM_VERSION
gem "decidim-top_comments", path: "."

gem "bootsnap", "~> 1.4"
gem "puma"
gem "uglifier", "~> 4.1"
gem "uri", ">= 1.0.3"

group :development, :test do
  gem "byebug", "~> 11.0", platform: :mri

  gem "decidim-dev", TOP_COMMENTS_DECIDIM_VERSION
end

group :development do
  gem "faker"
  gem "letter_opener_web"
  gem "web-console", "~> 3.5"
end
