default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("DB_POOL") { ENV.fetch("RAILS_MAX_THREADS", "5") } %>
  host: <%= ENV.fetch("DB_HOST") { ENV.fetch("DATABASE_HOST", "localhost") } %>
  port: <%= ENV.fetch("DB_PORT", "5432") %>

development:
  <<: *default
  min_messages: notice
  database: <%= ENV['DB_DATABASE'] %>
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>

test:
  <<: *default
  database: <%= ENV['TEST_DB_DATABASE'] %>
  username: <%= ENV['TEST_DB_USERNAME'] %>
  password: <%= ENV['TEST_DB_PASSWORD'] %>

integration:
  <<: *default
  database: <%= ENV['DB_DATABASE'] %>
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>

preprod:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
