source 'https://rubygems.org'

DECIDIM_VERSION = { git: 'https://github.com/gencat/decidim', branch: 'release/0.22-stable' }.freeze

gem "decidim", DECIDIM_VERSION

group :development, :test do
  gem "faker", ">= 1.8.4"
  gem "byebug", platform: :mri
  gem "bootsnap"
  gem "decidim-dev", DECIDIM_VERSION
  gem "rspec-rails"
  gem "listen"
end
# Declare your gem's dependencies in decidim-type.gemspec.
# Bundler will treat runtime dependencies like base dependencies, and
# development dependencies will be added by default to the :development group.
gemspec

# Declare any dependencies that are still in development here instead of in
# your gemspec. These might include edge Rails or gems from your path or
# Git. Remember to move these dependencies to your gemspec before releasing
# your gem to rubygems.org.

# To use a debugger
# gem 'byebug', group: [:development, :test]
