name: "[CI] Main Test"

on:
  push:
    branches:
      - master
      - release/*
      - "*-stable"
  pull_request:

env:
  RUBY_VERSION: 2.7.5
  NODE_VERSION: 16.9.1

jobs:
  test-app:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:11
        ports: ["5432:5432"]
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        env:
          POSTGRES_PASSWORD: postgres
    env:
      TEST_DB_DATABASE: participa_app_test
      TEST_DB_USERNAME: postgres
      TEST_DB_PASSWORD: postgres
      DB_HOST: localhost
      RECAPTCHA_SITE_KEY: 'recaptcha_site_key'
      RECAPTCHA_SECRET_KEY: 'recaptcha_secret_key'
    steps:
      - uses: actions/checkout@v2.0.0
        with:
          fetch-depth: 1

      - uses: ruby/setup-ruby@master
        with:
          ruby-version: ${{ env.RUBY_VERSION }}

      - uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
      - run: npm install

      - name: Recover Ruby dependency cache
        uses: actions/cache@v1
        with:
          path: ./vendor/bundle
          key: ${{ runner.OS }}-rubydeps-${{ hashFiles('Gemfile.lock') }}
          restore-keys: |
            ${{ runner.OS }}-rubydeps-${{ env.cache-name }}-
            ${{ runner.OS }}-rubydeps-
            ${{ runner.OS }}-

      - name: Set bundle local config configvendor/bundle path
        run: bundle config set --local path 'vendor/bundle'

      - name: Install Ruby deps
        uses: nick-invision/retry@v2
        with:
          timeout_minutes: 10
          max_attempts: 3
          retry_on: error
          command: bundle install --jobs 4 --retry 3

      - name: Setup database
        run: |
          RAILS_ENV=test bundle exec rake db:create
          RAILS_ENV=test bundle exec rake db:migrate

      - name: Run RSpec
        uses: nick-invision/retry@v2
        with:
          timeout_minutes: 10
          max_attempts: 3
          retry_on: error
          command: CI=1 RAILS_ENV=test bundle exec rspec --backtrace
