name: "[CI] Main Test"

on:
  push:
    branches:
      - main
      - release/*
      - "*-stable"
  pull_request:

env:
  RUBY_VERSION: 3.1.7
  NODE_VERSION: 16.9.1

jobs:
  test-app:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:11
        ports: ["5432:5432"]
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        env:
          POSTGRES_PASSWORD: postgres
    env:
      TEST_DB_DATABASE: participa_app_test
      TEST_DB_USERNAME: postgres
      TEST_DB_PASSWORD: postgres
      DB_HOST: localhost
      RECAPTCHA_SITE_KEY: 'recaptcha_site_key'
      RECAPTCHA_SECRET_KEY: 'recaptcha_secret_key'
      MACHINE_TRANSLATIONS_ENDPOINT_URL: "https://softcatala.example.org/machine_translations/endpoint"

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - uses: ruby/setup-ruby@master
        with:
          ruby-version: ${{ env.RUBY_VERSION }}

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
      - run: npm install

      - name: Recover Ruby dependency cache
        uses: actions/cache@v3
        with:
          path: ./vendor/bundle
          key: ${{ runner.OS }}-rubydeps-${{ hashFiles('Gemfile.lock') }}
          restore-keys: |
            ${{ runner.OS }}-rubydeps-${{ env.cache-name }}-
            ${{ runner.OS }}-rubydeps-
            ${{ runner.OS }}-

      - name: Set bundle local config configvendor/bundle path
        run: bundle config set --local path 'vendor/bundle'

      # chromedriver workaround
      - uses: nanasess/setup-chromedriver@v2
        with:
          chromedriver-version: 119.0.6045.105

      - name: List Chrome
        shell: "bash"
        run: apt list --installed | grep chrome

      - name: Remove Chrome
        shell: "bash"
        run: sudo apt remove google-chrome-stable

      - uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: 119.0.6045.105

      - name: Install ImageMagick
        run: sudo apt update && sudo apt install imagemagick

      - name: Install Ruby deps
        uses: nick-fields/retry@v3
        with:
          timeout_minutes: 10
          max_attempts: 3
          retry_on: error
          command: bundle install --jobs 4 --retry 3

      - name: Setup database
        run: |
          RAILS_ENV=test bundle exec rake db:create
          RAILS_ENV=test bundle exec rake db:migrate

      - name: Run RSpec
        uses: nick-fields/retry@v3
        with:
          timeout_minutes: 10
          max_attempts: 3
          retry_on: error
          command: CI=1 RAILS_ENV=test bundle exec rspec --backtrace

      # Prepare screenshots for upload
      - name: Prepare screenshots for upload
        run: RAILS_ENV=test bundle exec rails ci:screenshots:rename
        if: always()

      # Upload screenshots artifact
      - name: Upload screenshots
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: screenshot_artifact
          path: /home/runner/work/participa/participa/tmp/screenshots/
