name: "[CI] Recaptcha"

on:
  push:
    branches:
      - master
      - release/*
      - "*-stable"
  pull_request:

env:
  RUBY_VERSION: 3.1.1

jobs:
  test-report:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:11
        ports: ["5432:5432"]
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        env:
          POSTGRES_PASSWORD: postgres
    env:
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_HOST: localhost
    steps:
      - uses: actions/checkout@v2.0.0
        with:
          fetch-depth: 1

      - uses: ruby/setup-ruby@master
        with:
          ruby-version: ${{ env.RUBY_VERSION }}

      - name: Recover Ruby dependency cache
        uses: actions/cache@v3
        with:
          path: ./vendor/bundle
          key: ${{ runner.OS }}-rubydeps-${{ hashFiles('Gemfile.lock') }}
          restore-keys: |
            ${{ runner.OS }}-rubydeps-${{ env.cache-name }}-
            ${{ runner.OS }}-rubydeps-
            ${{ runner.OS }}-

      - name: Set bundle local config configvendor/bundle path
        run: bundle config set --local path 'vendor/bundle'

      # chromedriver workaround
      - uses: nanasess/setup-chromedriver@v2
        with:
          chromedriver-version: 119.0.6045.105

      - name: List Chrome
        shell: "bash"
        run: apt list --installed | grep chrome

      - name: Remove Chrome
        shell: "bash"
        run: sudo apt remove google-chrome-stable

      - uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: 119.0.6045.105

      - name: Install ImageMagick
        run: sudo apt install imagemagick

      - name: Install Ruby deps
        uses: nick-invision/retry@v2
        with:
          timeout_minutes: 10
          max_attempts: 3
          retry_on: error
          command: cd decidim-recaptcha && bundle install --jobs 4 --retry 3 

      - name: Generate recaptcha test_app
        run: |
          cd decidim-recaptcha
          bundle exec rake decidim:generate_external_test_app
          cd spec/decidim_dummy_app/
          RAILS_ENV=test bundle exec rails db:migrate

      - name: Run RSpec
        uses: nick-invision/retry@v2
        with:
          timeout_minutes: 10
          max_attempts: 3
          retry_on: error
          command: cd decidim-recaptcha && CI=1 PARTICIPA_SIMPLECOV=1 bundle exec rake --backtrace -t

      -  name: Upload coverage
         run: ./.github/upload_coverage.sh decidim-recaptcha $GITHUB_EVENT_PATH
