name: "[CI] Main Test"

on:
  push:
    branches:
      - master
      - release/*
      - "*-stable"
  pull_request:

env:
  RUBY_VERSION: 2.6.6

jobs:
  test-app:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:11
        ports: ["5432:5432"]
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        env:
          POSTGRES_PASSWORD: postgres
    env:
      DATABASE_HOST: localhost
      TEST_DB_DATABASE: participa_gencat_test
      TEST_DB_USERNAME: postgres
      TEST_DB_PASSWORD: postgres
    steps:
      - uses: actions/checkout@v2.0.0
        with:
          fetch-depth: 1

      - uses: ruby/setup-ruby@master
        with:
          ruby-version: ${{ env.RUBY_VERSION }}

      - name: Recover Ruby dependency cache
        uses: actions/cache@v1
        with:
          path: ./vendor/bundle
          key: ${{ runner.OS }}-rubydeps-${{ hashFiles('Gemfile.lock') }}
          restore-keys: |
            ${{ runner.OS }}-rubydeps-${{ env.cache-name }}-
            ${{ runner.OS }}-rubydeps-
            ${{ runner.OS }}-

      - name: Set bundle local config configvendor/bundle path
        run: bundle config set --local path 'vendor/bundle'

      - name: Install Ruby deps
        uses: nick-invision/retry@v2
        with:
          timeout_minutes: 10
          max_attempts: 3
          retry_on: error
          command: bundle install --jobs 4 --retry 3 

      - name: Create test database
        run: |
          RAILS_ENV=test bundle exec rails db:create
          RAILS_ENV=test bundle exec rails db:migrate

      - name: Setup Code Climate test-reporter
        run: |
          curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
          chmod +x ./cc-test-reporter
          ./cc-test-reporter before-build

      - name: Run RSpec
        uses: nick-invision/retry@v2
        with:
          timeout_minutes: 10
          max_attempts: 3
          retry_on: error
          command: CI=1 PARTICIPA_SIMPLECOV=1 bundle exec rake --backtrace -t

      - name: Publish code coverage
        run: |
          cp coverage/coverage.xml cobertura.xml
          export GIT_BRANCH="${GITHUB_REF/refs\/heads\//}"
          ./cc-test-reporter after-build -r "$CC_TEST_REPORTER_ID" -t cobertura
        env:
          CC_TEST_REPORTER_ID: 5841e84a171da0a7a56f23599f328444c88d7cb05cff9c78fc86c6404f2a1765
